"""Cross-reference the custom C_* client API against the extracted opcode table.

Neither half is much use alone. The opcode table says what exists on the wire but
not what triggers it; the addon Lua says what the client can ask for but not what
it sends. Matching them by name gives, per custom system: the API the UI calls,
the CMSGs a player action produces, and the SMSGs the server answers with.

That turns "go open the transmog window" into a measurable target - you know
which opcode ids a session should have produced, so coverage can be checked
against a denominator instead of felt.

Output: research/system-opcode-map.md
"""

import csv
import io
import os
import re
import collections

REPO    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OPCODES = os.path.join(REPO, "research", "ascension-opcodes.csv")
APILIST = os.path.join(REPO, "research", "custom-api-surface.txt")
OUTMD   = os.path.join(REPO, "research", "system-opcode-map.md")

STOCK_MAX = 1300   # stock 3.3.5a tops out around 0x501; above this is certainly custom

# Tokens too generic to identify a system on their own.
STOP = {"C", "GET", "SET", "IS", "CAN", "HAS", "INFO", "DATA", "LIST", "ALL",
        "BY", "ID", "THE", "OF", "AND", "NEW", "OLD", "UI", "MANAGER", "SERVICE"}


def camel_tokens(name):
    name = name[2:] if name.startswith("C_") else name
    parts = re.findall(r"[A-Z]+(?=[A-Z][a-z])|[A-Z][a-z]+|[A-Z]+|[0-9]+", name)
    return [p.upper() for p in parts if p.upper() not in STOP and len(p) > 2]


def load_opcodes():
    rows = []
    for r in csv.DictReader(io.open(OPCODES, encoding="utf-8")):
        if r["name"].strip():
            rows.append((int(r["opcode_dec"]), r["opcode_hex"], r["name"].strip()))
    return rows


def load_namespaces():
    ns = collections.defaultdict(list)
    for line in io.open(APILIST, encoding="utf-8"):
        line = line.strip()
        if line.startswith("C_") and "." in line:
            n, fn = line.split(".", 1)
            ns[n].append(fn)
    return ns


def main():
    opcodes = load_opcodes()
    custom  = [o for o in opcodes if o[0] > STOCK_MAX]
    ns      = load_namespaces()

    # A token shared by many namespaces (ITEM, BUILD, CHARACTER) identifies nothing.
    # Weight each token by how rare it is across namespaces, then give every opcode
    # to the single best-scoring namespace so systems partition instead of overlap.
    ns_tokens = {n: camel_tokens(n) for n in ns}
    freq = collections.Counter(t for toks in ns_tokens.values() for t in set(toks))

    def score(toks, words):
        s = 0.0
        for t in set(toks):
            if t in words:
                s += 1.0 / freq[t]          # rare token -> strong signal
        return s

    assign = {}
    for dec, hexv, name in custom:
        body  = re.sub(r"^(CMSG|SMSG|MSG)_", "", name)
        body  = re.sub(r"^CUSTOM_", "", body)
        words = set(body.split("_"))
        best, best_s = None, 0.0
        for n, toks in ns_tokens.items():
            s = score(toks, words)
            # tie-break toward the namespace with more matching tokens, then longer name
            if s > best_s or (s == best_s and best and s > 0 and
                              len([t for t in set(toks) if t in words]) >
                              len([t for t in set(ns_tokens[best]) if t in words])):
                best, best_s = n, s
        if best and best_s > 0:
            assign.setdefault(best, []).append((dec, hexv, name))

    matches, used = {}, set()
    for n, hits in assign.items():
        matches[n] = (ns[n], ns_tokens[n], sorted(hits))
        used.update(h[0] for h in hits)

    # Merge namespaces that resolve to the same opcode set (Build*, Wildcard*, ...)
    order = sorted(matches.items(), key=lambda kv: -len(kv[1][2]))

    out = []
    w = out.append
    w("# Custom system -> opcode map\n")
    w("Generated by `research/build_system_opcode_map.py` on 2026-09-04.\n")
    w("Joins the %d named opcodes above the stock 3.3.5 range (>%d) against the %d custom "
      "`C_*` API functions recovered from the addon Lua.\n"
      % (len(custom), STOCK_MAX, sum(len(v) for v in ns.values())))
    w("**Use this as the capture shot list.** For each system: the CMSG column is what a "
      "player action sends, the SMSG column is what the server answers with. A session that "
      "exercised a system should show its opcodes in the capture; if they are absent, that "
      "system was not actually covered.\n")
    w("---\n")

    for n, (fns, toks, hits) in order:
        cm = [h for h in hits if h[2].startswith("CMSG")]
        sm = [h for h in hits if h[2].startswith("SMSG")]
        ms = [h for h in hits if h[2].startswith("MSG")]
        w("## `%s` - %d API functions, %d opcodes\n" % (n, len(fns), len(hits)))
        w("Matched on: %s\n" % ", ".join("`%s`" % t for t in toks))
        w("| dir | dec | hex | opcode |")
        w("|---|---:|---|---|")
        for tag, group in (("C->S", cm), ("S->C", sm), ("both", ms)):
            for dec, hexv, name in sorted(group):
                w("| %s | %d | %s | `%s` |" % (tag, dec, hexv, name))
        w("")
        w("<details><summary>%d API functions</summary>\n" % len(fns))
        w("```")
        for f in sorted(fns):
            w("%s.%s" % (n, f))
        w("```")
        w("</details>\n")

    unmatched = [o for o in custom if o[0] not in used]
    w("---\n")
    w("## Custom opcodes with no matching API namespace: %d\n" % len(unmatched))
    w("These have no obvious client-side entry point in the addon Lua - they are either "
      "engine-level (movement, auth, GM), or belong to a system whose UI is built into the "
      "client binary rather than an addon. **They can only be captured by playing, never "
      "derived from files.**\n")
    w("```")
    for dec, hexv, name in unmatched:
        w("%5d  %-7s %s" % (dec, hexv, name))
    w("```")

    io.open(OUTMD, "w", encoding="utf-8", newline="\n").write("\n".join(out))

    print("systems matched      :", len(matches))
    print("custom opcodes       :", len(custom))
    print("  matched to a system:", len(used))
    print("  unmatched          :", len(unmatched))
    print("wrote", OUTMD)
    print()
    print("top systems by opcode count:")
    for n, (fns, toks, hits) in order[:18]:
        cm = sum(1 for h in hits if h[2].startswith("CMSG"))
        sm = sum(1 for h in hits if h[2].startswith("SMSG"))
        print("  %-30s %3d opcodes (%d C->S, %d S->C)  %3d api fns"
              % (n, len(hits), cm, sm, len(fns)))


if __name__ == "__main__":
    main()
